### ISSUE TITLE
Missing Things

### ISSUE THREAD

**Issue by fabio-filho** [paretogroup/omni-reports#8]
- Melhorar a passagem do event loop e do client session;
- Criação de testes;
- Facebook:
	- Aceitar inner fields no predicado;

**Comment by rafaelfbs** [comment]
I'll close this issue and break each point as a new issue.

**Comment by rafaelfbs** [comment]
@fabio-filho Could you explain in details about "Aceitar inner fields no predicado"? What do you propose as a contract in report definition.
